# Schema for the configuration files of the User registration password module.

user_registrationpassword.settings:
  type: config_object
  label: 'User registration password settings'
  mapping:
    registration:
      type: string
      label: 'User registration password type'
    registration_ftll_expire:
      type: boolean
      label: 'Expire activation link'
    registration_ftll_timeout:
      type: integer
      label: 'Expire activation timeout'

user_registrationpassword.mail:
  type: config_object
  label: 'User Registration email with password set settings'
  mapping:
    register_confirmation_with_pass:
      type: mail
      label: 'User registration email with password set'

user_registrationpassword.mail_original:
  type: config_object
  label: 'Used to store original core data used during uninstall'
  mapping:
    status_activated:
      type: mail
      label: 'Used to store original core values used during uninstall'
